# Generated by Django 2.2.7 on 2019-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('brewer', models.CharField(max_length=200)),
                ('abv', models.FloatField()),
                ('bitterness', models.IntegerField()),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
